name: ETL Pipeline CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create DBT profiles.yml
        shell: powershell
        run: |
          if (!(Test-Path "$env:USERPROFILE\.dbt")) {
              New-Item -ItemType Directory -Path "$env:USERPROFILE\.dbt"
          }

          $profileContent = @"
          my_project:
            target: dev
            outputs:
              dev:
                type: postgres
                host: $env:DB_HOST
                user: $env:DB_USER
                password: $env:DB_PASSWORD
                port: $env:DB_PORT
                dbname: $env:DB_NAME
                schema: public
          "@

          $profileContent | Out-File "$env:USERPROFILE\.dbt\profiles.yml"

        env:
          DB_HOST: ${{ secrets.host }}
          DB_USER: ${{ secrets.user }}
          DB_PASSWORD: ${{ secrets.password }}
          DB_PORT: ${{ secrets.port }}
          DB_NAME: ${{ secrets.dbname }}

      - name: Run DBT
        shell: powershell
        run: |
          cd my_project
          dbt run

      - name: Run Pytest
        shell: powershell
        run: |
          pytest
